### ISSUE TITLE
Add BigTable sink in Depot

### ISSUE THREAD

**Issue by MayurGubrele** [odpf/depot#54]
**Summary**
As part of this feature, we want to add support for Google’s Bigtable sink in Depot.

**Tasks**
- [ ] Implement Bigtable sink with batching with the hardcoded key in the depot
- [ ] Add input to column - family - qualifier mapping support
- [ ] Define RowKey template and implement RowKeyTemplateParser
- [ ] Error parser and error handling for bigtable sink
- [ ] Capture Bigtable metrics and add instrumentation(logging and monitoring)
- [ ] Add dashboard panels to capture BigTable sink metrics
- [ ] Documentation for bigtable sink
